# A. Import the libraries
library(readr)
library(tidyverse)
library(tidymodels)
library(vip)

library(doParallel)
registerDoParallel(cores = parallel::detectCores() - 1)


# B. Import data and Categorical Formatting
df <- read_csv("data_processed/Q1_Monthly_Regression_Data.csv")
View(df)
glimpse(df)
summary(df)

# Get unique values
unique(df$tax_category)
unique(df$income_level)

tax_levels <- c("Low Tax", "Medium Tax", "High Tax")
income_levels <- c("Low", "Middle", "High")

# Encode data
# Nominal data
df$country <- as.factor(df$country)
df$region <- as.factor(df$region)
df$fuel_type <- as.factor(df$fuel_type) # newly added

# Ordinal data
df$tax_category <- factor(df$tax_category, levels = tax_levels, ordered = TRUE)
df$income_level <- factor(df$income_level, levels = income_levels, ordered = TRUE)

# Sort the rows by year, month, and country.
# Newly added
df <- df |> arrange(year, month, country)

glimpse(df)


# C. Time-Series Data Splitting
set.seed(123)
data_split <- initial_time_split(df, prop = 0.80)
train_data <- training(data_split)
test_data <- testing(data_split)


# D. Rolling Vaidation Folds
# UPGRADE: Switched from random vfold_cv() to rolling_origin() time-windows.
# Also added "skip = 12" as testing every single month froze my laptop.
# "skip = 12" tells R to jump forward 1 year at a time, 
# cutting processing time by 80% while keeping the time-structure perfect.

folds <- rolling_origin(
  train_data,
  initial    = 36,   # Trains on 36 months of baseline history
  assess     = 6,    # Tests by forecasting 6 months forward
  skip       = 12,   # Jumps by 12 months to optimize processing speed
  cumulative = TRUE  # Accumulates historical data as time rolls forward
)


# E. Feature Engineering Recipe
price_recipe <- recipe(avg_retail_price ~ ., data = train_data) |>
  # Note: Exclude identifying chronological trackers from being used as direct predictors
  step_rm(year, month) |>
  # Handle nominal predictors
  step_novel(all_nominal_predictors()) |>
  step_dummy(all_nominal_predictors(), -all_outcomes()) |>
  # Note: Lag features to capture "historical behavior" of crude oil prices
  # This teaches the model that changes in raw oil take time to trickle down 
  # to the actual retail fuel pump.
  step_lag(avg_crude_price, lag = 1:2) |>
  # Engineered an interaction feature. This teaches the model that 
  # global oil shocks impact consumer prices differently based on how high 
  # that country's gas tax laws are.
  step_interact(terms = ~ starts_with("tax_category"):avg_crude_price) |>
  # Clean up empty rows generated by the lagging steps
  step_zv(all_predictors()) |>
  step_naomit(all_predictors())


# F. Engine Specifications

# Model 1: Linear Regression (Elastic Net)
linear_spec <- linear_reg(penalty = tune(), mixture = tune()) |>
  set_engine("glmnet") |>
  set_mode("regression")

# Model 2: XGBoost (Decision Tree Ensemble)
# Dropped tree count to 100 trees during this definition phase. 
# 1,000 trees choked my laptop's RAM. So I tune with 100 trees to find the best
# rules instantly, then scale it up to 1,000 trees later.
xgboost_spec <- boost_tree(
  trees = 100,
  tree_depth = tune(), #tune this
  learn_rate = tune(), #tune this
  min_n = tune() #tune this
) |>
  set_engine("xgboost") |>
  set_mode("regression")


# G. Workflow Mapping & Auditions (The Grid Tuning Loop)
# Combine recipe and models into a workflow set
model_set <- workflow_set(
  preproc = list(base_rec = price_recipe),
  models = list(linear = linear_spec, xgb = xgboost_spec)
)

# Set a parallel execution control so R distributes tasks to CPU cores
grid_control <- control_grid(
  save_pred     = TRUE,
  parallel_over = "resamples", 
  verbose       = TRUE
)

# Run the tuning/comparison (this grid-searches parameters for BOTH models)
# UPGRADE: Dropped the hyperparameter testing grid from 10 down to 5 to 
# make the search tightly optimized, and passed the parallel control.
tune_results <- model_set |>
  workflow_map(
    fn = "tune_grid",
    seed = 123,
    resamples = folds,
    grid = 5, # Tries 5 different combinations of parameters for each
    metrics = metric_set(rmse, mae),
    control  = grid_control,
    verbose = TRUE
  )

# Plot the results to see the winner
autoplot(tune_results, metric = "rmse")


# H. Master Fit Scale-Up (Th Winning Model)

# Extract the winning configuration rules discovered by R
winning_model_id <- "base_rec_xgb"

best_parameters <- tune_results |>
  extract_workflow_set_result(winning_model_id) |>
  select_best(metric = "rmse")

# UPGRADE: This is our master scale-up step. We take the winning rules 
# found by the script (tree_depth = 8, learn_rate = 0.316, min_n = 11) and 
# explicitly crank the power back up to 1,000 trees.
final_xgboost_spec <- boost_tree(
  trees      = 1000, 
  tree_depth = 8, 
  learn_rate = 0.316, 
  min_n      = 11 
) |>
  set_engine("xgboost") |>
  set_mode("regression")

base_wf   <- tune_results |> extract_workflow(winning_model_id)
final_wf  <- base_wf |> update_model(final_xgboost_spec)
final_fit <- last_fit(final_wf, data_split)


# I. Output Generation for Project Report
test_predictions <- final_fit |> augment()

extra_metrics <- metric_set(rmse, rsq, mae, mape)

cat("Final Test Set Performance Metrics \n")
test_predictions |>
  extra_metrics(truth = avg_retail_price, estimate = .pred) |>
  print()

# UPGRADE: Added a Feature Importance Plot
final_model_fit <- final_fit |> extract_fit_parsnip()

cat("\n Generating Feature Importance Plot \n")
final_model_fit |>
  vip(num_features = 10, geom = "col", aesthetics = list(fill = "steelblue")) |>
  print()

# UPGRADE: Added an Actual vs. Predicted Visual Scatterplot. 
cat("\n Generating Prediction Visualization \n")
ggplot(test_predictions, aes(x = avg_retail_price, y = .pred)) +
  geom_point(alpha = 0.4, color = "darkblue") +
  geom_abline(color = "red", linetype = "dashed", lwd = 1) +
  labs(
    title = "Actual vs. Predicted Retail Prices (Test Dataset)",
    x     = "Actual Average Retail Price",
    y     = "Predicted Average Retail Price"
  ) +
  theme_minimal()